clear; clc;
%% Exercise 4.2
%% 4.2
% Construct the Galois field GF(2^5) generated by p(X) = 1 + X^2 + X^5, 
% showing a table with the polynomial and binary representations of its 
% elements.

%%
% This exercise has been produced by hand. FIXME Ivan har taget en billede
% af siden hvor det blev lavet. Det skal indsættes her


%% 4.3
% 

syms a;
syms X;

y = (X + a)*(X + a^2)*(X + a^4)*(X + a^8)*(X + a^16)

z = expand(y)

